bases:
- ../../base/
namePrefix: ja-stage-
commonLabels:
  env: stage
namespace: stage
configMapGenerator:
- name: mongo-configmap
  envs:
  - mongo-configmap.env
secretGenerator:
- name: mongo-creds
  behavior: create
  envs:
  - mongo-secret.env  # This should be in env format for key pair values
patches:
- patch.yaml   # Patching to update NodePort