apiVersion: v1
kind: Service
metadata:
  name: mongo-db-service
  labels:
    app: mongodb-service
spec:
  selector:
    app: ja-mongo-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017