apiVersion: v1
kind: Service
metadata:
  name: ja-mongo-db-service
  labels:
    app: mongo-db-service
spec:
  selector:
    app: ja-mongo-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: ja-mongo-express-service
  labels:
    app: mongo-express-service
spec:
  selector:
    app: ja-mongo-express
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081 # Port accessible inside cluster
      targetPort: 8081 # Port accessible inside the pod
      nodePort: 30001 # Port accessible outside cluster