apiVersion: apps/v1
kind: Deployment
metadata:
  name: ja-mongo-express-deploy
  labels:
    app: ja-mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ja-mongo-express
  template:
    metadata:
      labels:
        app: ja-mongo-express
    spec:
      containers:
        - name: mongodb-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: ja-mongo-creds
                  key: mongodbadmin-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: ja-mongo-creds
                  key: mongodbadmin-password
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: ja-mongo-configmap
                  key: mongo_database_url