apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: ja-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ja-nginx
  template:
    metadata:
      labels:
        app: ja-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 8080
