apiVersion: v1
kind: Service
metadata:
  name: ja-nginx-service
  namespace: ja-nginx-env
spec:
    selector:
      app: ja-nginx
    type: NodePort
    ports:
     - protocol: TCP
       port: 80
       targetPort: 80
       nodePort: 30080
