bases:
- ../../base/
namePrefix: ja-pre-prod-
commonLabels:
  env: pre-prod
configMapGenerator:
- name: mongo-configmap
  files:
  - mongo-configmap.config
secretGenerator:
- name: mongo-creds
  behavior: create
  envs:
  - mongo-secret.env  # This should be in env format for key pair values
patches:
- patch.yaml   # Patching to update NodePort